### ISSUE TITLE
decode error with type of 'uint64'

### ISSUE THREAD

**Issue by holylousie** [mafintosh/protocol-buffers#41]
var buf = messages.Test.encode({
  num: 9663919463792641,   // num is 'uint64'
  payload: 'hello world'
})

var obj = messages.Test.decode(buf)
console.log(obj) 

result:{ num: 9663919463792640, payload: 'hello world' }

before : 9663919463792641
after: 9663919463792640

**Comment by mafintosh** [comment]
This is a javascript "error". 9663919463792641 is too big to represent as a javascript number so it gets truncated into 9663919463792640. Try opening a node repl and type in the number

```
$ node
> 9663919463792641
9663919463792640 
```

This is getting fixed in newer version of js though as 64 bit integers are being added although thats a *very* long term solution for this issue

**Comment by holylousie** [comment]
thanks~

**Comment by alexfernandez** [comment]
Do you think this might be solved by converting these 64 bit integers to strings? We don't even need to handle these big numbers, just keep them around as references. Conversion to ints is error prone anyway.

**Comment by mafintosh** [comment]
Sure that could work for some usecases. You can actually write your own [decoder](https://github.com/mafintosh/abstract-encoding) for `uint64` and pass that in as `{encodings: {uint64: yourCustomOne}}` to do this

**Comment by alexfernandez** [comment]
Thanks for the pointer. By the way, do you know of any such decoder? The standard [varint](library) does not provide support for converting big numbers to strings.

**Comment by mafintosh** [comment]
hmm no sorry but that sounds like a fun module to write!
